/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.33
 * Generated at: 2020-06-12 05:42:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Lesson;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import alcinfo.MemberBean;
import alcinfo.LessonBean;
import alcinfo.UtilMgr;

public final class leRead_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("/Lesson/../alcinfo/../login/loginSelect.jsp", Long.valueOf(1591939990194L));
    _jspx_dependants.put("/Lesson/../alcinfo/../login/idpwdSearch.jsp", Long.valueOf(1591940008332L));
    _jspx_dependants.put("/Lesson/../alcinfo/headerSearch.jsp", Long.valueOf(1591939954623L));
    _jspx_dependants.put("/Lesson/../alcinfo/../login/loginMain.jsp", Long.valueOf(1591940026413L));
    _jspx_dependants.put("/Lesson/../alcinfo/footer.jsp", Long.valueOf(1591666707000L));
    _jspx_dependants.put("/Lesson/../alcinfo/../login/idSearch.jsp", Long.valueOf(1591940015392L));
    _jspx_dependants.put("/Lesson/../alcinfo/../login/pwdChange.jsp", Long.valueOf(1591940092509L));
    _jspx_dependants.put("/Lesson/../alcinfo/../login/memberSelect.jsp", Long.valueOf(1591940056910L));
    _jspx_dependants.put("/Lesson/../alcinfo/../login/pwdSearch.jsp", Long.valueOf(1591940067916L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("alcinfo.LessonBean");
    _jspx_imports_classes.add("alcinfo.MemberBean");
    _jspx_imports_classes.add("alcinfo.UtilMgr");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- leRead.jsp -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      alcinfo.LessonMgr mgr = null;
      mgr = (alcinfo.LessonMgr) _jspx_page_context.getAttribute("mgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (mgr == null){
        mgr = new alcinfo.LessonMgr();
        _jspx_page_context.setAttribute("mgr", mgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');
      alcinfo.MemberMgr Mmgr = null;
      Mmgr = (alcinfo.MemberMgr) _jspx_page_context.getAttribute("Mmgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (Mmgr == null){
        Mmgr = new alcinfo.MemberMgr();
        _jspx_page_context.setAttribute("Mmgr", Mmgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write("\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");
	String id = "";
	String url = "LessonMain.jsp?pageValue=top";
	LessonBean lebean = null;
	int num = UtilMgr.parseInt(request, "num"); 
	
	if(request.getParameter("id") == null) {
		response.sendRedirect(url);
	} else {
		id = request.getParameter("id");
		lebean = mgr.getLesson(id);
		session.setAttribute("lebean", lebean);
		mgr.upLeCount(num);
		
		lebean.setId(id);
		  System.out.println("선생님아이디는"+id);
		
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Team Read</title>\r\n");
      out.write("\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("google.charts.load(\"current\",{packages:['corechart']});\r\n");
      out.write("\r\n");
      out.write("function columnChart1(arrayList) {\r\n");
      out.write("\t// 실 데이터를 가진 데이터테이블 객체를 반환하는 메소드\r\n");
      out.write("\t \r\n");
      out.write("\t\r\n");
      out.write("\t arrayList = eval('('+arrayList+')');\r\n");
      out.write("\r\n");
      out.write("\tvar dataTable = new google.visualization.DataTable();\r\n");
      out.write("\tdataTable.addColumn('string','Date');\r\n");
      out.write("\tdataTable.addColumn('number','register');\r\n");
      out.write("\tdataTable.addRows(arrayList);\r\n");
      out.write("\t// 옵션객체 준비\r\n");
      out.write("\tvar options = {\r\n");
      out.write("\ttitle: '날짜 별 등록 학생수',\r\n");
      out.write("\tlegend: 'top',\r\n");
      out.write("\t colors: ['#FCBC7E']\r\n");
      out.write("\t};\r\n");
      out.write("\t// 차트를 그릴 영역인 div 객체를 가져옴\r\n");
      out.write("\tvar objDiv = document.getElementById('column_chart_div1');\r\n");
      out.write("\t// 인자로 전달한 div 객체의 영역에 컬럼차트를 그릴수 있는 차트객체를 반환\r\n");
      out.write("\tvar chart = new google.visualization.ColumnChart(objDiv);\r\n");
      out.write("\t// 차트객체에 데이터테이블과 옵션 객체를 인자로 전달하여 차트 그리는 메소드\r\n");
      out.write("\tchart.draw(dataTable, options);\r\n");
      out.write("\t/* var chart = new google.charts.Bar(objDiv);\r\n");
      out.write("\t// 차트객체에 데이터테이블과 옵션 객체를 인자로 전달하여 차트 그리는 메소드\r\n");
      out.write("\tchart.draw(dataTable,google.charts.Bar.convertOptions(options)); */\r\n");
      out.write("} // drawColumnChart1()의 끝\r\n");
      out.write("\r\n");
      out.write("function graph(){\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\tdataType:\"text\",\r\n");
      out.write("\t\r\n");
      out.write("\turl:'columnChart1.jsp?id=");
      out.print(id);
      out.write("',\r\n");
      out.write("\tsuccess:function(result){\r\n");
      out.write("\tcolumnChart1(result);\r\n");
      out.write("\t}, \r\n");
      out.write("\terror:function(request, error){\r\n");
      out.write("\t\talert(\"에러\");\r\n");
      out.write("\t\talert(\"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("\t} \r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction moveQnA(){\r\n");
      out.write("\t\t\turl = \"le_QnA.jsp?lq_lnum=\"+");
      out.print(lebean.getNum());
      out.write(";\r\n");
      out.write("\t\t\twindow.open(url, \"Le_QnA\", \"width=800, height=500, top=200, left=400\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction insert() // no ';' here\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t    var elem = document.getElementById(\"myButton1\");\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t\tlocation.href=\"insertStudentProc.jsp?id=");
      out.print(id);
      out.write("&num=");
      out.print(lebean.getNum());
      out.write("\";\r\n");
      out.write("\t\t\t   \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction cancel(){\r\n");
      out.write("\t\t\tvar elem = document.getElementById(\"myButton2\");\r\n");
      out.write("\t\t\tlocation.href=\"deleteStudentProc.jsp?id=");
      out.print(id);
      out.write("&num=");
      out.print(lebean.getNum());
      out.write("\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction goReport() {\r\n");
      out.write("\t\turl = \"../Report/reportReceiptLInf.jsp?stopid=");
      out.print(id);
      out.write("\";\r\n");
      out.write("\t\twindow.open(url, \"GoReport\", \"width=400, height=350, top=200, left=300\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("<!-- 헤더1 -->\r\n");
      out.write("\r\n");

 	int random=(int)(Math.random()*10+1);
  
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"../alcinfo/headerStyle.css\" rel=\"stylesheet\">\r\n");
      out.write("<script>\r\n");
      out.write("function btnmouseUp(){\r\n");
      out.write("\tvar button=document.getElementById(\"button\");\r\n");
      out.write("\tbutton.style.color=\"rgb(240,240,240)\";\r\n");
      out.write("}\r\n");
      out.write("function btnmouseOut(){\r\n");
      out.write("\tvar button=document.getElementById(\"button\");\r\n");
      out.write("\tbutton.style.color=\"white\";\r\n");
      out.write("}\r\n");
      out.write("function check() {\r\n");
      out.write("\tif(document.searchFrm.keyWord.value==\"\"){\r\n");
      out.write("\t\talert(\"검색어를 입력하세요.\");\r\n");
      out.write("\t\tdocument.searchFrm.keyWord.focus();\r\n");
      out.write("\t\tlocation.href=\"SearchPage.jsp\";\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tdocument.searchFrm.submit();\r\n");
      out.write("}\r\n");
      out.write("function openlogoutProc(){\r\n");
      out.write("\tlocation.href=\"../login/logoutProc.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"margin: 0px;\">\r\n");
      out.write("<!-- loginSelect.jsp -->\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function openloginSelect() {\r\n");
      out.write("\tdocument.getElementById(\"loginSelect\").style.display = 'block';\r\n");
      out.write("}\r\n");
      out.write("function closeloginSelect() {\r\n");
      out.write("\tdocument.getElementById(\"loginSelect\").style.display = 'none';\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"idpwdstyle.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<div id=\"loginSelect\" class=\"loginSelect\">\r\n");
      out.write("\t<button onclick=\"closeloginSelect();\">close</button>\r\n");
      out.write("\t<form class=\"idpwd-content\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"loginleft\">\r\n");
      out.write("\t\t\t\t\t\t<p align=\"center\">일반 회원이신가요?</p>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"idpwdhr\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"로그인\" class=\"loginb\" \r\n");
      out.write("\t\t\t\t\t\tonclick=\"closeloginSelect(); openloginMain();\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"vline\"></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"loginright\">\r\n");
      out.write("\t\t\t\t\t\t<p align=\"center\">선생님이신가요?</p>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"idpwdhr\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"로그인\" class=\"loginb\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"closeloginSelect(); openloginMain();\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write("<!-- loginMain.jsp -->\r\n");
      out.write("\r\n");

		request.setCharacterEncoding("UTF-8");

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction openloginMain() {\r\n");
      out.write("\t\tdocument.getElementById(\"loginMain\").style.display = 'block';\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction closeloginMain() {\r\n");
      out.write("\t\tdocument.getElementById(\"loginMain\").style.display = 'none';\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction openidpwdSearch() {\r\n");
      out.write("\t\tdocument.getElementById(\"idpwdSearch\").style.display = 'block';\r\n");
      out.write("\t}\r\n");
      out.write("\twindow.onclick = function (event) {\r\n");
      out.write("\t  if (event.target == loginMain) {\r\n");
      out.write("\t\t  document.getElementById(\"loginMain\").style.display = \"none\";\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction loginCheck() {\r\n");
      out.write("\t\tif (document.loginFrm.lid.value.trim() == \"\") {\r\n");
      out.write("\t\t\talert(\"아이디를 입력해 주세요.\");\r\n");
      out.write("\t\t\tdocument.loginFrm.lid.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif (document.loginFrm.lpwd.value == \"\") {\r\n");
      out.write("\t\t\talert(\"비밀번호를 입력해 주세요.\");\r\n");
      out.write("\t\t\tdocument.loginFrm.lpwd.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.loginFrm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"../login/idpwdstyle.css\" rel=\"stylesheet\">\r\n");
      out.write("<div id=\"loginMain\" class=\"loginMain1\">\r\n");
      out.write("\t<button onclick=\"closeloginMain();\">close</button>\r\n");
      out.write("\t<form class=\"idpwd-content\" name=\"loginFrm\" method=\"post\" action=\"../login/loginProc.jsp\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><p style=\"margin-bottom:10px;\">로그인</p></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t<table border=\"1\" width=\"400px\">\r\n");
      out.write("\t\t\t\t\t\t<tr style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\">아이디</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"173px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"idpwdtext\" style=\"height:30px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"lid\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td rowspan=\"2\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a onclick=\"loginCheck();\">로그인</a>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr style=\"height:30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<td align=\"center\">비밀번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"173px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"idpwdtext\" style=\"height:30px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"lpwd\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"130px\"><input type=\"button\" \r\n");
      out.write("\t\t\t\tonclick=\"closeloginMain(); openidpwdSearch();\" value=\"ID/PW찾기\"></td>\r\n");
      out.write("\t\t\t\t<td><p style=\"margin-top:15px;\">아직 회원이 아니신가요?</p></td>\r\n");
      out.write("\t\t\t\t<td><a onclick=\"closeloginMain(); openmemberSelect();\" class=\"im\"><b>회원가입</b></a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write("<!-- memberSelect.jsp -->\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("function openmemberSelect() {\r\n");
      out.write("\tdocument.getElementById(\"memberSelect\").style.display = 'block';\r\n");
      out.write("}\r\n");
      out.write("function closememberSelect() {\r\n");
      out.write("\tdocument.getElementById(\"memberSelect\").style.display = 'none';\r\n");
      out.write("}\r\n");
      out.write("function mhref1() {\r\n");
      out.write("\tdocument.getElementById(\"memberSelect\").style.display = 'none';\r\n");
      out.write("\tlocation.href=\"../login/insertMember1.jsp\";\r\n");
      out.write("}\r\n");
      out.write("function mhref2() {\r\n");
      out.write("\tdocument.getElementById(\"memberSelect\").style.display = 'none';\r\n");
      out.write("\tlocation.href=\"../login/insertMember2.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"idpwdstyle.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<div id=\"memberSelect\" class=\"memberSelect\">\r\n");
      out.write("\t<button onclick=\"closememberSelect();\">close</button>\r\n");
      out.write("\t<form class=\"idpwd-content\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"loginleft\">\r\n");
      out.write("\t\t\t\t\t\t<p align=\"center\">학생 회원가입</p>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"idpwdhr\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"회원가입\" class=\"loginb\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"javascript:mhref1()\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"vline\"></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"loginright\">\r\n");
      out.write("\t\t\t\t\t\t<p align=\"center\">선생님 회원가입</p>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"idpwdhr\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"회원가입\" class=\"loginb\"\r\n");
      out.write("\t\t\t\t\t\tonclick=\"javascript:mhref2()\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write("<!-- idpwdSearch.jsp -->\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction closeidpwdSearch() {\r\n");
      out.write("\t\tdocument.getElementById(\"idpwdSearch\").style.display = 'none';\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction openidSearch() {\r\n");
      out.write("\t\tdocument.getElementById(\"idSearch\").style.display = 'block';\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction openpwdSearch() {\r\n");
      out.write("\t\tdocument.getElementById(\"pwdSearch\").style.display = 'block';\r\n");
      out.write("\t}\r\n");
      out.write("\twindow.onclick = function (event) {\r\n");
      out.write("\t  if (event.target == idpwdSearch) {\r\n");
      out.write("\t\t  document.getElementById(\"idpwdSearch\").style.display = \"none\";\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"../login/idpwdstyle.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<div id=\"idpwdSearch\" class=\"idpwdSearch\">\r\n");
      out.write("\t<button onclick=\"closeidpwdSearch();\">close</button>\r\n");
      out.write("\t<form class=\"idpwd-content\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"loginleft\">\r\n");
      out.write("\t\t\t\t\t\t<p align=\"center\">아이디 찾기</p>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"idpwdhr\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"찾기\" class=\"loginb\" \r\n");
      out.write("\t\t\t\t\t\tonclick=\"closeidpwdSearch(); openidSearch();\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"vline\"></div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<div class=\"loginright\">\r\n");
      out.write("\t\t\t\t\t\t<p align=\"center\">비밀번호 찾기</p>\r\n");
      out.write("\t\t\t\t\t\t<hr class=\"idpwdhr\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" value=\"찾기\" class=\"loginb\"\r\n");
      out.write("\t\t\t\t\t\t onclick=\"closeidpwdSearch(); openpwdSearch();\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write("<!-- idSearch.jsp -->\r\n");
      out.write("\r\n");

	request.setCharacterEncoding("UTF-8");

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction closeidSearch() {\r\n");
      out.write("\t\tdocument.getElementById(\"idSearch\").style.display = 'none';\r\n");
      out.write("\t}\r\n");
      out.write("\twindow.onclick = function (event) {\r\n");
      out.write("\t  if (event.target == idSearch) {\r\n");
      out.write("\t\t  document.getElementById(\"idSearch\").style.display = \"none\";\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction idSearch(isname, isphone) {\r\n");
      out.write("\t\tif(isname==\"\") {\r\n");
      out.write("\t\t\talert(\"이름을 입력하세요.\");\r\n");
      out.write("\t\t\tdocument.isfrm.isname.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(isphone==\"\") {\r\n");
      out.write("\t\t\talert(\"휴대폰 번호를 입력하세요.\");\r\n");
      out.write("\t\t\tdocument.isfrm.isphone.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\turl = \"../login/idSearchProc.jsp?isname=\"+isname+\"&isphone=\"+isphone;\r\n");
      out.write("\t\twindow.open(url, \"idSearchProc\", \"width=300, height=150, top=200, left=400\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"../login/idpwdstyle.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<div id=\"idSearch\" class=\"idSearch\">\r\n");
      out.write("\t<button onclick=\"closeidSearch();\">close</button>\r\n");
      out.write("\t<form class=\"idpwd-content\" name=\"isfrm\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><p style=\"margin-bottom:10px;\">아이디 찾기</p></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<table border=\"1\" width=\"400px\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"140px\" align=\"center\">이름</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"260px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" style=\"width:260px; height:30px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"isname\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"140px\" align=\"center\">휴대폰 번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"260px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" style=\"width:260px; height:30px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"isphone\" maxlength=\"11\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"로그인\" class=\"loginb\" style=\"margin-top:10px; width:100px;\"\r\n");
      out.write("\t\t\t\t\tonclick=\"closeidSearch(); openloginMain();\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"찾기\" class=\"loginb\" style=\"margin-top:10px; margin-left:194px; width:100px;\" \r\n");
      out.write("\t\t\t\t\tonclick=\"idSearch(this.form.isname.value, this.form.isphone.value);\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>");
      out.write('\r');
      out.write('\n');
      out.write("<!-- pwdSearch.jsp -->\r\n");
      out.write("\r\n");
      member.MemberMgr psmgr = null;
      psmgr = (member.MemberMgr) _jspx_page_context.getAttribute("psmgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (psmgr == null){
        psmgr = new member.MemberMgr();
        _jspx_page_context.setAttribute("psmgr", psmgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("UTF-8");
	String pscheck = "", psid = "", psname = "", psphone = "";

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction closepwdSearch() {\r\n");
      out.write("\t\tdocument.getElementById(\"pwdSearch\").style.display = 'none';\r\n");
      out.write("\t}\r\n");
      out.write("\twindow.onclick = function (event) {\r\n");
      out.write("\t  if (event.target == pwdSearch) {\r\n");
      out.write("\t\t  document.getElementById(\"pwdSearch\").style.display = \"none\";\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction pwdSearch() {\r\n");
      out.write("\t\tif(document.psfrm1.psid.value.trim()==\"\") {\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\tdocument.psfrm1.psid.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.psfrm1.psname.value.trim()==\"\") {\r\n");
      out.write("\t\t\talert(\"이름을 입력하세요.\");\r\n");
      out.write("\t\t\tdocument.psfrm1.psname.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.psfrm1.psphone.value.trim()==\"\") {\r\n");
      out.write("\t\t\talert(\"휴대폰 번호를 입력하세요.\");\r\n");
      out.write("\t\t\tdocument.psfrm1.psphone.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tdocument.psfrm2.pscheck.value=\"1\";\r\n");
      out.write("\t\t\tdocument.psfrm2.psid.value=document.psfrm1.psid.value;\r\n");
      out.write("\t\t\tdocument.psfrm2.psname.value=document.psfrm1.psname.value;\r\n");
      out.write("\t\t\tdocument.psfrm2.psphone.value=document.psfrm1.psphone.value;\r\n");
      out.write("\t\t\tdocument.psfrm2.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction openpwdSearch1() {\r\n");
      out.write("\t\t");
 if(request.getParameter("pscheck")!=null) {
				psid = request.getParameter("psid");
				psname = request.getParameter("psname");
				psphone = request.getParameter("psphone");
				boolean result3 = psmgr.pwdSearch(psid, psname, psphone);
				if(result3) {
			
      out.write("\r\n");
      out.write("\t\t\t\talert(\"새로운 비밀번호로 변경하세요.\");\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"pwdChange\").style.display = 'block';\r\n");
      out.write("\t\t\t");
  } else { 
      out.write("\r\n");
      out.write("\t\t\t\talert(\"정보와 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"pwdSearch\").style.display = 'block';\r\n");
      out.write("\t\t\t");
  } 
      out.write("\r\n");
      out.write("\t\t");
 } 
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"../login/idpwdstyle.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<body onload=\"javascript:openpwdSearch1()\">\r\n");
      out.write("<div id=\"pwdSearch\" class=\"pwdSearch\">\r\n");
      out.write("\t<button onclick=\"closepwdSearch();\">close</button>\r\n");
      out.write("\t<form class=\"idpwd-content\" name=\"psfrm1\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><p style=\"margin-bottom:10px;\">비밀번호 찾기</p></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<table border=\"1\" width=\"400px\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"140px\" align=\"center\">아이디</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"260px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" style=\"width:260px; height:30px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"psid\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"140px\" align=\"center\">이름</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"260px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" style=\"width:260px; height:30px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"psname\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"140px\" align=\"center\">휴대폰 번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"260px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" style=\"width:260px; height:30px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"psphone\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"right\"><input type=\"button\" value=\"찾기\" class=\"loginb\" \r\n");
      out.write("\t\t\t\tstyle=\"margin-top:10px;\" onclick=\"pwdSearch();\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<form name=\"psfrm2\" method=\"post\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"pscheck\" value=\"");
      out.print(pscheck);
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"psid\" value=\"");
      out.print(psid);
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"psname\" value=\"");
      out.print(psname);
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"psphone\" value=\"");
      out.print(psphone);
      out.write("\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>");
      out.write('\r');
      out.write('\n');
      out.write("<!-- pwdChange.jsp -->\r\n");
      out.write("\r\n");
      member.MemberMgr pcmgr = null;
      pcmgr = (member.MemberMgr) _jspx_page_context.getAttribute("pcmgr", javax.servlet.jsp.PageContext.PAGE_SCOPE);
      if (pcmgr == null){
        pcmgr = new member.MemberMgr();
        _jspx_page_context.setAttribute("pcmgr", pcmgr, javax.servlet.jsp.PageContext.PAGE_SCOPE);
      }
      out.write('\r');
      out.write('\n');

	request.setCharacterEncoding("EUC-KR");

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction closepwdChange() {\r\n");
      out.write("\t\tdocument.getElementById(\"pwdChange\").style.display = 'none';\r\n");
      out.write("\t}\r\n");
      out.write("\twindow.onclick = function (event) {\r\n");
      out.write("\t  if (event.target == pwdChange) {\r\n");
      out.write("\t\t  document.getElementById(\"pwdChange\").style.display = \"none\";\r\n");
      out.write("\t  }\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction pcpwdCheck() {\r\n");
      out.write("\t\tif(document.pcfrm.pcpwd.value != document.pcfrm.pcrepwd.value){\r\n");
      out.write("\t\t\talert(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("\t\t\tdocument.pcfrm.pcrepwd.value=\"\";\r\n");
      out.write("\t\t\tdocument.pcfrm.pcrepwd.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tdocument.pcfrm.submit();\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<link href=\"../login/idpwdstyle.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"pwdChange\" class=\"pwdChange\">\r\n");
      out.write("\t<button onclick=\"closepwdChange();\">close</button>\r\n");
      out.write("\t<form class=\"idpwd-content\" name=\"pcfrm\" method=\"post\" action=\"../login/pwdChangeProc.jsp\">\r\n");
      out.write("\t\t<table>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><p style=\"margin-bottom:10px;\">비밀번호 변경</p></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<table border=\"1\" width=\"400px\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"140px\" align=\"center\">새 비밀번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"260px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" style=\"width:260px; height:30px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"pcpwd\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"140px\" align=\"center\">비밀번호 확인</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"260px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" style=\"width:260px; height:30px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"pcrepwd\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"right\">\r\n");
      out.write("\t\t\t\t\t<input type=\"button\" value=\"저장\" class=\"loginb\" onclick=\"pcpwdCheck();\">\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"pcid\" value=\"");
      out.print(request.getParameter("psid"));
      out.write("\">\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"top\" align=\"center\">\r\n");
      out.write("\t\t<span> ※과도한 사교육은 올바른 교육이 아닙니다.&nbsp;&nbsp; <a\r\n");
      out.write("\t\t\thref=\"../CS/custCenter.jsp?cust_page=ccBestBoard.jsp\">고객센터</a>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<form name=\"searchFrm\" action=\"../alcinfo/SearchPage.jsp\">\r\n");
      out.write("\t\t\t<table style=\"margin-top: 70px;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"../alcinfo/cards-gallery.jsp\"><img src=\"../img/home.png\"\r\n");
      out.write("\t\t\t\t\t\t\t\twidth=\"80px\" style=\"margin-right: 30px\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"searchTotal\">\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"search\" type=\"text\" name=\"keyWord\"> <input\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"button\" type=\"submit\" value=\"검색\" onmouseover=\"btnmouseUp();\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonmouseout=\"btnmouseOut();\" onClick=\"javascript:check()\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"catagory\" align=\"center\"\r\n");
      out.write("\t\t\tstyle=\"background-color: rgb(034, 200, 211);\">\r\n");
      out.write("\t\t\t<a href=\"../Academy/AcademyMain.jsp?pageValue=top\">학원</a> \r\n");
      out.write("\t\t\t<a\thref=\"../Lesson/LessonMain.jsp?pageValue=top\">과외선생님</a> \r\n");
      out.write("\t\t\t<a\thref=\"../Student/StudentMain.jsp?pageValue=count\">학생</a> \r\n");
      out.write("\t\t\t<a\thref=\"../Community/communityList.jsp?pageValue=free\">커뮤니티</a> \r\n");
      out.write("\t\t\t<a\thref=\"../Payment/buyPoint.jsp\" style=\"color:yellow;\"><img src=\"../img/won.png\" width=\"20\" height=\"20\">포인트</a>\r\n");
      out.write("\t\t\t");
 if(session.getAttribute("idKey")==null){
      out.write("\r\n");
      out.write("\t\t\t<input type=\"button\" onclick=\"openloginSelect();\" class=\"openlm\" value=\"로그인\">\r\n");
      out.write("\t\t\t");
}else{ 
      out.write("\r\n");
      out.write("\t\t\t<input type=\"button\" onclick=\"openlogoutProc();\" class=\"openlm\" value=\"로그아웃\">\r\n");
      out.write("\t\t\t<a href=\"\">마이페이지</a>\r\n");
      out.write("\t\t\t");
} 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"banner\" align=\"center\"\r\n");
      out.write("\t\tstyle=\"width: 100%; background-color: rgb(240, 240, 240); box-shadow: 0px 0px 10px #c0c0c0;\">\r\n");
      out.write("\t\t<a href=\"\"><img src=\"../img/banner");
      out.print(random );
      out.write(".jpg\"\r\n");
      out.write("\t\t\tstyle=\"width: 70%; height: 300px\"></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<form name=\"cart\" action=\"\">\r\n");
      out.write("\t\t<table width=\"70%\" align=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t\t<table width=\"100%\" style=\"font-size: 20; background: rgb(250, 248, 235);\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"25%\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"../img/banner1.jpg\"\twidth=\"100%\" height=\"250\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"60%\" height=\"100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table width=\"100%\"  style=\"font-size: 20;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"30%\">선생님명 / 성별</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"70%\">");
      out.print(lebean.getName());
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print(lebean.getGender() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"30%\">과외가능지역</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"70%\">");
      out.print(lebean.getArea() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"30%\">전화번호</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"70%\">");
      out.print(lebean.getPhone() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"30%\">과외 가능한 과목</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"70%\">");
      out.print(lebean.getLeclass() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr height=\"35\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"30%\">과외중인 학생 수</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"70%\">");
      out.print(lebean.getStudent() );
      out.write("명</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"30%\">재학(졸업)중인 학교</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"70%\">");
      out.print(lebean.getSchool_name() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr height=\"40\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"30%\">비고</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td width=\"70%\">");
      out.print(lebean.getEtc() );
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td width=\"15%\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table name=\"buttonTable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=\"button\" value=\"문의하기\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 20;\" onclick=\"moveQnA();\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=\"button\" value=\"잘못된정보 신고하기\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 20;\" onclick=\"goReport();\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=\"button\" value=\"신청하기\" id=\"myButton1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 20;\" onclick=\"insert()\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td><input type=\"button\" value=\"취소하기\" id=\"myButton2\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 20;\" onclick=\"cancel()\"></input>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<table width=\"70%\" height=\"280\" align=\"center\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td width=\"30%\" align=\"center\">\r\n");
      out.write("\t\t\t\t<div style=\"border:10px solid #FCBC7E; border-radius:15px; padding:20px\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" id=\"btn\" onclick=\"graph()\" >그래프 보기</button>\r\n");
      out.write("\t\t\t\t<div id=\"column_chart_div1\"  style=\"height: 440px; width:300px;\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td width=\"70%\" align=\"center\">\r\n");
      out.write("\t\t\t\t<div style=\"border:10px solid #36ada9; border-radius:15px; padding:20px\">\r\n");
      out.write("\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "lessonAskList.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("<!-- 저작권 나타내는 제일 밑에 창 -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\t\t<hr>\r\n");
      out.write("\t\t<p style=\"color: gray\">\r\n");
      out.write("\t\t\t© 2020 BusanIT403, Inc. All rights reserved<br> ADDRESS : 부산광역시\r\n");
      out.write("\t\t\t부산진구 부전2동 중앙대로 708 403호, 부산파이낸스센터 <br> TEL : 051-753-5600 <br>\r\n");
      out.write("\t\t\t홈페이지 내의 모든 저작물은 BusanIT403의 것이며, 무단으로 복제 및 사용이 불가능 합니다. <br>\r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</html>\r\n");

	}

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
